#!/bin/bash
# This script decides if it's been long enough since the last time it was loaded to 
# attempt a git pull to automatically recieve updates
declare -i load_now;
declare -i load_lastCheckout;
declare -i load_senseLastCheckout;
load_now=`date +%s`;
if [ `uname` = Darwin ]
then
  load_lastCheckout=`stat -t %s -f %c ~/.deadlyicon/.svn`;
else
  load_lastCheckout=`date +%s -r ~/.deadlyicon/.svn`;
fi
load_senseLastCheckout=`expr $load_now - $load_lastCheckout`;

if [ $load_senseLastCheckout -gt 86400 ]
then
	echo updating common bash files
  (cd $BASH_COMMON_PATH; git pull)
fi

unset load_now;
unset load_lastCheckout;
unset load_senseLastCheckout;
source $BASH_COMMON_PATH/common
