#!/bin/bash
pull_bash_common(){
  echo pulling bash common
  (cd $BASH_COMMON_PATH; git pull)
  echo FUCK YOU > ~/tmp/out
}
#
# # This script decides if it's been long enough since the last time it was loaded to
# # attempt a git pull to automatically recieve updates
# declare -i load_now;
# declare -i load_lastCheckout;
# declare -i load_senseLastCheckout;
# load_now=`date +%s`;
# if [ `uname` = Darwin ]
# then
#   load_lastCheckout=`stat -t %s -f %c $BASH_COMMON_PATH/.git`;
# else
#   load_lastCheckout=`date +%s -r $BASH_COMMON_PATH/.git`;
# fi
# load_senseLastCheckout=`expr $load_now - $load_lastCheckout`;
#
# if [ $load_senseLastCheckout -gt 86400 ]
# then
#   echo updating common bash files
#   (cd $BASH_COMMON_PATH; git pull)
# fi
#
# unset load_now;
# unset load_lastCheckout;
# unset load_senseLastCheckout;
source $BASH_COMMON_PATH/common
if [ -f "$BASH_COMMON_PATH/commons/`uname`" ]; then
  source "$BASH_COMMON_PATH/commons/`uname`"
fi


screen -d -m -S UPDATING_BASH_COMMON pull_bash_common