#!/usr/bin/env bash

## Set PATH so it includes user's private script dir if it exists
[[ -d ~/Library/Bin       ]] && PATH=~/Library/Bin:$PATH
[[ -d ~/.gem/ruby/1.8/bin ]] && PATH=~/.gem/ruby/1.8/bin:$PATH

bind "set completion-ignore-case on"

export LC_CTYPE=en_US.UTF-8
export HISTFILESIZE=1000000000
export HISTSIZE=1000000
export HTTPD_CONF="/private/etc/apache2/httpd.conf"
export HTTPD_LOGS="/private/var/log/apache2/"

alias ls='/bin/ls -GF'
alias o='open'
alias e="mate"
alias pf="open -a Path\ Finder"
alias restart-quicksilver='sudo killall Quicksilver; sleep 1; open /Applications/Quicksilver.app/'
alias wrapinquotes='ruby -e "puts \$stdin.read.split(\"\n\").map{|l| \"\\\"#{l}\\\"\"}" '
alias resource='(cd ~; source .bash_profile)'

pslist(){
 ps aux | head -n 1;
 ps aux | grep -i "$1"
}
booksearch(){ 
 find /Users/deadlyicon/Documents/Books/ -iname "*$1*"; 
}
volume(){
 osascript -e "set volume $1"
}

export GEMDIR=`gem env gemdir`
gemdoc() {
  open $GEMDIR/doc/`$(which ls) $GEMDIR/doc | grep $1 | sort | tail -1`/rdoc/index.html
}
_gemdoc() {
  COMPREPLY=($(compgen -W '$(`which ls` $GEMDIR/doc)' -- ${COMP_WORDS[COMP_CWORD]}))
  return 0
}
complete -o default -o nospace -F _gemdoc gemdoc

# shopt -s autocd

# alias hibernate="sudo pmset -a hibernatemode 5; sudo shutdown -s now && sudo pmset -a hibernatemode 3"

# Commands for Terminal Usage
tab(){
osascript 2>/dev/null <<EOF
  tell application "System Events"
    tell process "Terminal" to keystroke "t" using command down
  end
  tell application "Terminal"
    activate
    do script with command "cd $PWD" in window 1
    do script with command "$*" in window 1
  end tell
EOF
}